### ISSUE TITLE
Not getting notification emails

### ISSUE THREAD

**Issue by kingjon3377** [PenoaksDevOps/HolyWorlds-Issues#32]
(I was sure there was an open issue about this, but now all I can find is #13, which was fixed back in 2018.)

The most recent "topic reply" or "new topic" notification emails I've received were in November 2019, and the most recent "forum post notification" email was October 2019. The forum hasn't seen *much* activity in the last year, but there have definitely been posts to threads I'm subscribed to in that time.

As I noted in #13, the cause could be something having gone wrong with the code of the server, something wrong with the configuration of the server, or some metaphorical gremlins having convinced my email provider (Gmail) that these notifications are so likely to be spam that they should be dropped rather than put in my spam box.

**Comment by aidan-casey** [comment]
I'll ping someone about this. I suspect stuff was never setup correctly when servers last changed.

**Comment by aidan-casey** [comment]
SMTP is disabled. The board is attempting and failing to use the PHP mail function.

**Comment by BarelyAPrincess** [comment]
With the SMTP disabled, the site is supposed to be using an alternative function `mailgun_send()` (over the normal PHP `mail()` function) which uses the Mailgun cURL API to deliver the e-mail to the client. After some investigating it turns out the cURL PHP library was not installed and there was an HTTP 500 error being thrown because it couldn’t find the function `curl_init()`. Installed library and everything seems to function as intended.

**Comment by aidan-casey** [comment]
@BarelyAPrincess any reason we are using that over SMTP?

**Comment by BarelyAPrincess** [comment]
It's because phpBB 3.0.12 is so outdated that it's SMTP protocol, if I remember correctly, does not support the latest security standards put in place by various email providers including Gmail and Mailgun.

I was also not going to use PHP's send `sendmail()` function since I needed a reliable delivery route. And maintaining a 100% whitelisted email server these days is next to impossible.

**Comment by aidan-casey** [comment]
Gotcha. Yet another reason I wish we were on 3.3. 😁
